### ISSUE TITLE
关于纠错后准确率的提升

### ISSUE THREAD

**Issue by SZHL** [tiantian91091317/OCR-Corrector#2]
你好，我前段时间也在尝试用bert去做ocr的纠错，可能因为自己技术有些粗糙，在和此项目实现思路大致相同的情况下只带来了不到一个百分点的准确率提升。虽然说ocr本身的准确和应用的场景应该不一样，还是想作为参考请问一下，纠错后ocr的准确大概提高了多少呢，谢谢

**Comment by tiantian91091317** [comment]
纠错这方面的准确率和召回率怎么样呢？badcase是什么样的呢？
在我们的场景，基础OCR的准确率超过99%，BERT大概能实现50%的错误召回率，可以解决掉大部分的形近字问题。

**Comment by SZHL** [comment]
谢谢，我之前对接的ocr在基础测试中字符级别准确率在99%以上，sequence级别在97%左右。然后困难样本集上字符级准确率在97%，sequence级别在93%。badcase主要是在短句及实体名称过多的句子中，bert对于masked token的预测效果不够理想。我只在困难集上测试的，字符级别提升到98%，sequence基本提升不到一个点

**Comment by tiantian91091317** [comment]
谢谢你的反馈，看样子你的一个错误的sequence里面错字超过一个，所以字符召回率30%左右但是sequence只有10%。不知道你有没有尝试过多回合纠错？
不过如果是短句或者实体名称过多的句子有问题，那可能只能拼接句子或者继续训练了。

**Comment by SZHL** [comment]
哦哦非常感谢，有思路了
