### ISSUE TITLE
char_meta_file这个文件是干嘛的，如何生成？

### ISSUE THREAD

**Issue by deep-practice** [tiantian91091317/OCR-Corrector#3]

**Comment by tiantian91091317** [comment]
这个文件是用来计算**汉字字形的编辑距离**的。好比**英文单词**的编辑距离是用单词**字母序列**计算的，汉字没有办法直接计算，但可以把汉字转化为**笔画结构序列**。
生成：从[这个项目](https://github.com/cjkvi/cjkvi-ids)可以拿到基本数据，在它的基础上，可以递归地生成所有汉字的笔画结构序列ids（需补充200多个基础汉字的ids）。reame里面有我生成的这个文件的地址。
