### ISSUE TITLE
run error

### ISSUE THREAD

**Issue by gaojingqian** [tiantian91091317/OCR-Corrector#7]
Hi,
调用"ocr_res_corrected = corrector.correct(ocr_results, recog_probs, biz_type)"显示corrector没有correct成员

**Comment by tiantian91091317** [comment]
你好，也许你应该更新一下代码？这段应该是以前的版本

**Comment by xxAna** [comment]
@tiantian91091317 没有找到新的版本，请问已经更新了吗

**Comment by tiantian91091317** [comment]
嗯，是的，8月份就更新了……

**Comment by tiantian91091317** [comment]
你可以看看你拉取的最新版本是不是 991a50a？
