### ISSUE TITLE
不能纠错

### ISSUE THREAD

**Issue by superdu12138** [tiantian91091317/OCR-Corrector#8]
你好，我下载了模型和相似字的那个文本，直接用说明中的例子验证一下效果，发现都不能够纠正过来，是不是什么地方漏掉了？
测试代码：
![image](https://user-images.githubusercontent.com/20619835/100426913-95d29680-30cc-11eb-9e44-5786b3414294.png)

结果：
![image](https://user-images.githubusercontent.com/20619835/100426686-3f655800-30cc-11eb-8f20-70c400008b0b.png)

**Comment by w-Bro** [comment]
我也是这样，请问解决了吗

**Comment by tiantian91091317** [comment]
你好，因为业务上调用的时候是多条文本一个 batch，所以这里的输入定义的是 text = ['本着平等、白愿、诚信、互利的原则']，probs = [[0.99, 0.99, 0.99, 0.99, 0.99, 0.78, 0.99, 0.99, 0.99, 0.99, 0.99, 0.99, 0.99, 0.99, 0.99, 0.99]]
举例的时候没考虑到（我的锅）
