### ISSUE TITLE
请问这里的bert预训练是哪个模型呢

### ISSUE THREAD

**Issue by xxAna** [tiantian91091317/OCR-Corrector#9]
请问这里的bert预训练是哪个模型呢？是否还可以用自己的数据进一步finetune呢

**Comment by tiantian91091317** [comment]
你好，就是google官方发布的那一版，https://github.com/google-research/bert  
可以用自己的数据进行 finetune，具体方法就按照google官方给出的就行

**Comment by xxAna** [comment]
好嘞，谢谢您！
